services:
  postgres-innovacion:
    image: postgres:latest
    container_name: postgres-innovacion
    restart: unless-stopped
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: comercialx
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin-innovacion:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-innovacion
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: innovacioncomercialx@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres-innovacion

  backend-innovacion:
    build: .
    container_name: backend-innovacion
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5002:5002"
    depends_on:
      - postgres-innovacion

volumes:
  pgdata:
